
import java.math.RoundingMode;
import java.text.DecimalFormat;

public class SGPACalculator extends javax.swing.JFrame {

    /**
     * Creates new form SGPACalculator
     */
    public SGPACalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        in1 = new javax.swing.JTextField();
        in2 = new javax.swing.JTextField();
        in3 = new javax.swing.JTextField();
        in4 = new javax.swing.JTextField();
        in5 = new javax.swing.JTextField();
        in6 = new javax.swing.JTextField();
        in7 = new javax.swing.JTextField();
        in8 = new javax.swing.JTextField();
        in9 = new javax.swing.JTextField();
        ex1 = new javax.swing.JTextField();
        ex2 = new javax.swing.JTextField();
        ex3 = new javax.swing.JTextField();
        ex4 = new javax.swing.JTextField();
        ex5 = new javax.swing.JTextField();
        ex6 = new javax.swing.JTextField();
        ex7 = new javax.swing.JTextField();
        ex8 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        ex9 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        c5 = new javax.swing.JTextField();
        c6 = new javax.swing.JTextField();
        c8 = new javax.swing.JTextField();
        c7 = new javax.swing.JTextField();
        c9 = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        sgpa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sanskrit Text", 1, 36)); // NOI18N
        jLabel1.setText("VTU Grading System");

        jLabel2.setFont(new java.awt.Font("Sanskrit Text", 1, 20)); // NOI18N
        jLabel2.setText("Theory");

        jLabel3.setFont(new java.awt.Font("Sanskrit Text", 1, 20)); // NOI18N
        jLabel3.setText("Internals");

        jLabel4.setFont(new java.awt.Font("Sanskrit Text", 1, 20)); // NOI18N
        jLabel4.setText("Externals");

        jLabel5.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel5.setText("Subject 1");

        jLabel6.setFont(new java.awt.Font("Sanskrit Text", 1, 20)); // NOI18N
        jLabel6.setText("Credit");

        jLabel7.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel7.setText("Subject 2");

        jLabel8.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel8.setText("Subject 4");

        jLabel9.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel9.setText("Subject 3");

        jLabel10.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel10.setText("Subject 5");

        jLabel11.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel11.setText("Subject 6");

        jLabel12.setFont(new java.awt.Font("Sanskrit Text", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Labs");

        jLabel13.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Lab 1");

        jLabel14.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Lab 2");

        jLabel15.setFont(new java.awt.Font("Sanskrit Text", 1, 18)); // NOI18N
        jLabel15.setText("Additional");

        in1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        in2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        in3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        in4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        in5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        in6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        in7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        in8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        in9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ex9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sgpa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel16.setBackground(new java.awt.Color(40, 140, 240));
        jLabel16.setFont(new java.awt.Font("Sanskrit Text", 3, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Total");

        jLabel17.setBackground(new java.awt.Color(40, 140, 240));
        jLabel17.setFont(new java.awt.Font("Sanskrit Text", 3, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SGPA");

        jButton1.setBackground(new java.awt.Color(240, 140, 40));
        jButton1.setFont(new java.awt.Font("Sanskrit Text", 2, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(40, 240, 40));
        jButton2.setFont(new java.awt.Font("Sanskrit Text", 2, 18)); // NOI18N
        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(240, 40, 40));
        jButton3.setFont(new java.awt.Font("Sanskrit Text", 2, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(in2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(193, 193, 193)
                                        .addComponent(sgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 60, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(c9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(c8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(in2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(in3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(in4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(in5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(in6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(in7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(in8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(in9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        in1.setText("");in2.setText("");in3.setText("");in4.setText("");in5.setText("");in6.setText("");in7.setText("");in8.setText("");in9.setText("");
        ex1.setText("");ex2.setText("");ex3.setText("");ex4.setText("");ex5.setText("");ex6.setText("");ex7.setText("");ex8.setText("");ex9.setText("");
        c1.setText("");c2.setText("");c3.setText("");c4.setText("");c5.setText("");c6.setText("");c7.setText("");c8.setText("");c9.setText("");
        total.setText("");sgpa.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i1,i2,i3,i4,i5,i6,i7,i8,i9,e1,e2,e3,e4,e5,e6,e7,e8,e9,p1,p2,p3,p4,p5,p6,p7,p8,p9,g1,g2,g3,g4,g5,g6,g7,g8,g9,t;
        double gpa=0.0;
        i1=Integer.parseInt(in1.getText());i2=Integer.parseInt(in2.getText());i3=Integer.parseInt(in3.getText());i4=Integer.parseInt(in4.getText());
        i5=Integer.parseInt(in5.getText());i6=Integer.parseInt(in6.getText());i7=Integer.parseInt(in7.getText());i8=Integer.parseInt(in8.getText());i9=Integer.parseInt(in9.getText());
        e1=Integer.parseInt(ex1.getText());e2=Integer.parseInt(ex2.getText());e3=Integer.parseInt(ex3.getText());e4=Integer.parseInt(ex4.getText());
        e5=Integer.parseInt(ex5.getText());e6=Integer.parseInt(ex6.getText());e7=Integer.parseInt(ex7.getText());e8=Integer.parseInt(ex8.getText());e9=Integer.parseInt(ex9.getText());
        p1=Integer.parseInt(c1.getText());p2=Integer.parseInt(c2.getText());p3=Integer.parseInt(c3.getText());p4=Integer.parseInt(c4.getText());
        p5=Integer.parseInt(c5.getText());p6=Integer.parseInt(c6.getText());p7=Integer.parseInt(c7.getText());p8=Integer.parseInt(c8.getText());p9=Integer.parseInt(c9.getText());
        int sub1=i1+e1;int sub2=i2+e2;int sub3=i3+e3;int sub4=i4+e4;int sub5=i5+e5;int sub6=i6+e6;int sub7=i7+e7;int sub8=i8+e8;int sub9=i9+e9;sub9=sub9*2;
        t=i1+i2+i3+i4+i5+i6+i7+i8+i9+e1+e2+e3+e4+e5+e6+e7+e8+e9;
        total.setText(Integer.toString(t));
        if(sub1>=50&&sub1<101)
            g1=(sub1/10)+1;
        else if(sub1>=45&&sub1<50)
            g1=5;
        else if(sub1>=40&&sub1<45)
            g1=4;
        else
            g1=0;
        if(sub1>=50&&sub1<101)
            g1=(sub1/10)+1;
        else if(sub1>=45&&sub1<50)
            g1=5;
        else if(sub1>=40&&sub1<45)
            g1=4;
        else
            g1=0;
        if(sub2>=50&&sub2<101)
            g2=(sub2/10)+1;
        else if(sub2>=45&&sub2<50)
            g2=5;
        else if(sub2>=40&&sub2<45)
            g2=4;
        else
            g2=0;
        if(sub3>=50&&sub3<101)
            g3=(sub3/10)+1;
        else if(sub3>=45&&sub3<50)
            g3=5;
        else if(sub3>=40&&sub3<45)
            g3=4;
        else
            g3=0;
        if(sub4>=50&&sub4<101)
            g4=(sub4/10)+1;
        else if(sub4>=45&&sub4<50)
            g4=5;
        else if(sub4>=40&&sub4<45)
            g4=4;
        else
            g4=0;
        if(sub5>=50&&sub5<101)
            g5=(sub5/10)+1;
        else if(sub5>=45&&sub5<50)
            g5=5;
        else if(sub5>=40&&sub5<45)
            g5=4;
        else
            g5=0;
        if(sub6>=50&&sub6<101)
            g6=(sub6/10)+1;
        else if(sub6>=45&&sub6<50)
            g6=5;
        else if(sub6>=40&&sub6<45)
            g6=4;
        else
            g6=0;
        if(sub7>=50&&sub7<101)
            g7=(sub7/10)+1;
        else if(sub7>=45&&sub7<50)
            g7=5;
        else if(sub7>=40&&sub7<45)
            g7=4;
        else
            g7=0;
        if(sub8>=50&&sub8<101)
            g8=(sub8/10)+1;
        else if(sub8>=45&&sub8<50)
            g8=5;
        else if(sub8>=40&&sub9<45)
            g8=4;
        else
            g8=0;
        if(sub9>=50&&sub9<101)
            g9=(sub9/10)+1;
        else if(sub9>=45&&sub9<50)
            g9=5;
        else if(sub9>=40&&sub9<45)
            g9=4;
        else
            g9=0;
        int m1,m2,m3,m4,m5,m6,m7,m8,m9;
        m1=p1*g1;m2=p2*g2;m3=p3*g3;m4=p4*g4;m5=p5*g5;m6=p6*g6;m7=p7*g7;m8=p8*g8;m9=p9*g9;
        int tc=m1+m2+m3+m4+m5+m6+m7+m8+m9;
        int tp=p1+p2+p3+p4+p5+p6+p7+p8+p9;
        gpa=tc/tp;
        System.out.println(m1+" "+m2+" "+m3+" "+m4+" "+m5+" "+m6+" "+m7+" "+m8+" "+m9);
        DecimalFormat df= new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.CEILING);
        sgpa.setText(df.format(gpa));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SGPACalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SGPACalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SGPACalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SGPACalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SGPACalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JTextField c5;
    private javax.swing.JTextField c6;
    private javax.swing.JTextField c7;
    private javax.swing.JTextField c8;
    private javax.swing.JTextField c9;
    private javax.swing.JTextField ex1;
    private javax.swing.JTextField ex2;
    private javax.swing.JTextField ex3;
    private javax.swing.JTextField ex4;
    private javax.swing.JTextField ex5;
    private javax.swing.JTextField ex6;
    private javax.swing.JTextField ex7;
    private javax.swing.JTextField ex8;
    private javax.swing.JTextField ex9;
    private javax.swing.JTextField in1;
    private javax.swing.JTextField in2;
    private javax.swing.JTextField in3;
    private javax.swing.JTextField in4;
    private javax.swing.JTextField in5;
    private javax.swing.JTextField in6;
    private javax.swing.JTextField in7;
    private javax.swing.JTextField in8;
    private javax.swing.JTextField in9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField sgpa;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
